# Generated by Django 6.0.7 on 2026-08-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=200)),
                (
                    "role_de",
                    models.CharField(max_length=200, verbose_name="Rolle (Deutsch)"),
                ),
                (
                    "role_it",
                    models.CharField(
                        max_length=200, verbose_name="Rolle (Italienisch)"
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="contacts/"),
                ),
            ],
            options={
                "verbose_name": "Kontaktperson",
                "verbose_name_plural": "Kontaktpersonen",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="FAQItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "question_de",
                    models.CharField(max_length=255, verbose_name="Frage (Deutsch)"),
                ),
                (
                    "question_it",
                    models.CharField(
                        max_length=255, verbose_name="Frage (Italienisch)"
                    ),
                ),
                (
                    "answer_de",
                    models.TextField(
                        help_text="Einfaches HTML wie <strong>/<a> ist erlaubt.",
                        verbose_name="Antwort (Deutsch)",
                    ),
                ),
                (
                    "answer_it",
                    models.TextField(
                        help_text="Einfaches HTML wie <strong>/<a> ist erlaubt.",
                        verbose_name="Antwort (Italienisch)",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ-Eintrag",
                "verbose_name_plural": "FAQ",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="HotelRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=200)),
                (
                    "description_de",
                    models.CharField(
                        max_length=255, verbose_name="Beschreibung (Deutsch)"
                    ),
                ),
                (
                    "description_it",
                    models.CharField(
                        max_length=255, verbose_name="Beschreibung (Italienisch)"
                    ),
                ),
                ("url", models.URLField(blank=True)),
            ],
            options={
                "verbose_name": "Hotel-Empfehlung",
                "verbose_name_plural": "Hotel-Empfehlungen",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="LocationCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Emoji/Symbol, z.B. ⛪", max_length=10
                    ),
                ),
                (
                    "title_de",
                    models.CharField(max_length=200, verbose_name="Titel (Deutsch)"),
                ),
                (
                    "title_it",
                    models.CharField(
                        max_length=200, verbose_name="Titel (Italienisch)"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name des Ortes (nicht übersetzt).", max_length=200
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                (
                    "map_embed_url",
                    models.URLField(
                        blank=True,
                        help_text="Google-Maps 'Embed a map' URL.",
                        max_length=1000,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="locations/"),
                ),
            ],
            options={
                "verbose_name": "Ort",
                "verbose_name_plural": "Orte",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SiteImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Interner Bezeichner, z.B. 'hero'.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="site/")),
                (
                    "alt_de",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Alt-Text (Deutsch)"
                    ),
                ),
                (
                    "alt_it",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Alt-Text (Italienisch)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bild",
                "verbose_name_plural": "Bilder",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="StoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "title_de",
                    models.CharField(max_length=200, verbose_name="Titel (Deutsch)"),
                ),
                (
                    "title_it",
                    models.CharField(
                        max_length=200, verbose_name="Titel (Italienisch)"
                    ),
                ),
                (
                    "date_label",
                    models.CharField(
                        blank=True,
                        help_text="z.B. 'Sommer 2020' (nicht übersetzt).",
                        max_length=100,
                    ),
                ),
                ("text_de", models.TextField(verbose_name="Text (Deutsch)")),
                ("text_it", models.TextField(verbose_name="Text (Italienisch)")),
                ("image", models.ImageField(blank=True, null=True, upload_to="story/")),
            ],
            options={
                "verbose_name": "Story-Kapitel",
                "verbose_name_plural": "Unsere Geschichte",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TextBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Interner Bezeichner, z.B. 'hero_subtitle'.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Beschreibung für die Verwaltung, z.B. 'Hero – Untertitel'.",
                        max_length=200,
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        blank=True,
                        help_text="Abschnitt, z.B. 'Hero', 'Geschenke'.",
                        max_length=100,
                    ),
                ),
                ("text_de", models.TextField(verbose_name="Text (Deutsch)")),
                ("text_it", models.TextField(verbose_name="Text (Italienisch)")),
            ],
            options={
                "verbose_name": "Textbaustein",
                "verbose_name_plural": "Textbausteine",
                "ordering": ["group", "key"],
            },
        ),
        migrations.CreateModel(
            name="TimelineStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("time", models.CharField(help_text="z.B. 16:30", max_length=20)),
                (
                    "title_de",
                    models.CharField(max_length=200, verbose_name="Titel (Deutsch)"),
                ),
                (
                    "title_it",
                    models.CharField(
                        max_length=200, verbose_name="Titel (Italienisch)"
                    ),
                ),
                (
                    "description_de",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Beschreibung (Deutsch)",
                    ),
                ),
                (
                    "description_it",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Beschreibung (Italienisch)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programmpunkt",
                "verbose_name_plural": "Tagesablauf",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TravelInfoCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Emoji/Symbol, z.B. ✈", max_length=10
                    ),
                ),
                (
                    "title_de",
                    models.CharField(max_length=200, verbose_name="Titel (Deutsch)"),
                ),
                (
                    "title_it",
                    models.CharField(
                        max_length=200, verbose_name="Titel (Italienisch)"
                    ),
                ),
                (
                    "body_de",
                    models.TextField(
                        help_text="Einfaches HTML wie <strong> ist erlaubt.",
                        verbose_name="Text (Deutsch)",
                    ),
                ),
                (
                    "body_it",
                    models.TextField(
                        help_text="Einfaches HTML wie <strong> ist erlaubt.",
                        verbose_name="Text (Italienisch)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reise-Info",
                "verbose_name_plural": "Reise-Infos",
                "ordering": ["order"],
            },
        ),
    ]
