# Generated by Django 6.0.7 on 2026-08-21 18:39

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sitecontent", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faqitem",
            name="answer_de",
            field=django_ckeditor_5.fields.CKEditor5Field(
                verbose_name="Antwort (Deutsch)"
            ),
        ),
        migrations.AlterField(
            model_name="faqitem",
            name="answer_it",
            field=django_ckeditor_5.fields.CKEditor5Field(
                verbose_name="Antwort (Italienisch)"
            ),
        ),
        migrations.AlterField(
            model_name="textblock",
            name="text_de",
            field=django_ckeditor_5.fields.CKEditor5Field(
                verbose_name="Text (Deutsch)"
            ),
        ),
        migrations.AlterField(
            model_name="textblock",
            name="text_it",
            field=django_ckeditor_5.fields.CKEditor5Field(
                verbose_name="Text (Italienisch)"
            ),
        ),
        migrations.AlterField(
            model_name="travelinfocard",
            name="body_de",
            field=django_ckeditor_5.fields.CKEditor5Field(
                verbose_name="Text (Deutsch)"
            ),
        ),
        migrations.AlterField(
            model_name="travelinfocard",
            name="body_it",
            field=django_ckeditor_5.fields.CKEditor5Field(
                verbose_name="Text (Italienisch)"
            ),
        ),
    ]
