# Generated by Django 6.0.7 on 2026-08-21 18:43

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "sitecontent",
            "0002_alter_faqitem_answer_de_alter_faqitem_answer_it_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="locationcard",
            name="description_de",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True,
                help_text="Optional. Wird zwischen Titel und Adresse angezeigt.",
                verbose_name="Beschreibung (Deutsch)",
            ),
        ),
        migrations.AddField(
            model_name="locationcard",
            name="description_it",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True,
                help_text="Optional. Wird zwischen Titel und Adresse angezeigt.",
                verbose_name="Beschreibung (Italienisch)",
            ),
        ),
    ]
