# Generated by Django 6.0.7 on 2026-08-21 18:46

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitecontent", "0003_locationcard_description_de_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GiftsSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_de",
                    models.CharField(max_length=200, verbose_name="Titel (Deutsch)"),
                ),
                (
                    "title_it",
                    models.CharField(
                        max_length=200, verbose_name="Titel (Italienisch)"
                    ),
                ),
                (
                    "text_de",
                    django_ckeditor_5.fields.CKEditor5Field(
                        verbose_name="Text (Deutsch)"
                    ),
                ),
                (
                    "text_it",
                    django_ckeditor_5.fields.CKEditor5Field(
                        verbose_name="Text (Italienisch)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Geschenke-Inhalt",
                "verbose_name_plural": "Geschenke-Inhalt",
            },
        ),
    ]
