# Generated by Django 6.0.7 on 2026-08-21 18:48

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sitecontent", "0004_giftssection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storyitem",
            name="text_de",
            field=django_ckeditor_5.fields.CKEditor5Field(
                verbose_name="Text (Deutsch)"
            ),
        ),
        migrations.AlterField(
            model_name="storyitem",
            name="text_it",
            field=django_ckeditor_5.fields.CKEditor5Field(
                verbose_name="Text (Italienisch)"
            ),
        ),
    ]
