# Generated by Django 6.0.7 on 2026-08-21 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitecontent", "0005_alter_storyitem_text_de_alter_storyitem_text_it"),
    ]

    operations = [
        migrations.CreateModel(
            name="RSVPSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, verbose_name="Anmeldende Person"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-Mail")),
                (
                    "no_of_guests",
                    models.PositiveSmallIntegerField(verbose_name="Anzahl Gäste"),
                ),
                ("message", models.TextField(blank=True, verbose_name="Nachricht")),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Eingegangen am"
                    ),
                ),
            ],
            options={
                "verbose_name": "Anmeldung",
                "verbose_name_plural": "Anmeldungen",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="RSVPGuest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "meal",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Menüwahl"
                    ),
                ),
                (
                    "allergies",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Allergien / Unverträglichkeiten",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guests",
                        to="sitecontent.rsvpsubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gast",
                "verbose_name_plural": "Gäste",
            },
        ),
    ]
