# Generated by Django 6.0.7 on 2026-08-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitecontent", "0006_rsvpsubmission_rsvpguest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storyitem",
            name="date_label",
        ),
        migrations.AddField(
            model_name="storyitem",
            name="date_label_de",
            field=models.CharField(
                blank=True,
                help_text="z.B. 'Sommer 2020'.",
                max_length=100,
                verbose_name="Datum (Deutsch)",
            ),
        ),
        migrations.AddField(
            model_name="storyitem",
            name="date_label_it",
            field=models.CharField(
                blank=True,
                help_text="z.B. 'Estate 2020'.",
                max_length=100,
                verbose_name="Datum (Italienisch)",
            ),
        ),
    ]
