# Generated by Django 6.0.7 on 2026-08-30 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sitecontent",
            "0007_remove_storyitem_date_label_storyitem_date_label_de_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="timelinestep",
            name="icon_image",
            field=models.FileField(
                blank=True,
                help_text="Optional — ohne Upload wird ein Standard-Icon angezeigt.",
                null=True,
                upload_to="timeline_icons/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg", "svg"]
                    )
                ],
                verbose_name="Icon-Bild (PNG, JPEG oder SVG)",
            ),
        ),
    ]
