# Generated by Django 6.0.7 on 2026-08-30 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitecontent", "0008_timelinestep_icon_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationcard",
            name="icon_image",
            field=models.FileField(
                blank=True,
                help_text="Optional — ersetzt das Emoji-Icon.",
                null=True,
                upload_to="location_icons/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg", "svg"]
                    )
                ],
                verbose_name="Icon-Bild (PNG, JPEG oder SVG)",
            ),
        ),
        migrations.AddField(
            model_name="travelinfocard",
            name="icon_image",
            field=models.FileField(
                blank=True,
                help_text="Optional — ersetzt das Emoji-Icon.",
                null=True,
                upload_to="travel_icons/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg", "svg"]
                    )
                ],
                verbose_name="Icon-Bild (PNG, JPEG oder SVG)",
            ),
        ),
        migrations.AlterField(
            model_name="locationcard",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Emoji/Symbol, z.B. ⛪ (Fallback, falls kein Icon-Bild hochgeladen ist)",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="travelinfocard",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Emoji/Symbol, z.B. ✈ (Fallback, falls kein Icon-Bild hochgeladen ist)",
                max_length=10,
            ),
        ),
    ]
