# Generated by Django 6.0.8 on 2026-09-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0009_locationcard_icon_image_travelinfocard_icon_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rsvpguest',
            options={'ordering': ['is_child', 'id'], 'verbose_name': 'Gast', 'verbose_name_plural': 'Gäste'},
        ),
        migrations.AddField(
            model_name='rsvpguest',
            name='age',
            field=models.CharField(blank=True, max_length=20, verbose_name='Alter'),
        ),
        migrations.AddField(
            model_name='rsvpguest',
            name='is_child',
            field=models.BooleanField(default=False, verbose_name='Kind'),
        ),
        migrations.AddField(
            model_name='rsvpsubmission',
            name='no_of_children',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Anzahl Kinder'),
        ),
    ]
