"""
Django settings for weddingsite project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import yaml
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_yaml_config() -> dict:
    config_path = BASE_DIR / 'config.yaml'
    if not config_path.exists():
        return {}

    with config_path.open('r', encoding='utf-8') as fh:
        data = yaml.safe_load(fh) or {}

    if not isinstance(data, dict):
        raise ImproperlyConfigured('config.yaml must contain a mapping at the root level.')

    return data


def _as_bool(value, default=False):
    if value is None:
        return default
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        return value.strip().lower() in {'1', 'true', 'yes', 'on'}
    return bool(value)


def _as_list(value, default=None):
    if value is None:
        return list(default or [])
    if isinstance(value, list):
        return value
    if isinstance(value, str):
        return [item.strip() for item in value.split(',') if item.strip()]
    raise ImproperlyConfigured('ALLOWED_HOSTS must be a list or comma-separated string.')


CONFIG = _load_yaml_config()

# Shared password required to view the site
SITE_PASSWORD = os.environ.get('SITE_PASSWORD', CONFIG.get('SITE_PASSWORD', 'changeme'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', CONFIG.get('SECRET_KEY'))
if not SECRET_KEY:
    raise ImproperlyConfigured('Set SECRET_KEY in config.yaml or as an environment variable.')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _as_bool(os.environ.get('DEBUG', CONFIG.get('DEBUG', True)), default=True)

ALLOWED_HOSTS = _as_list(
    os.environ.get('ALLOWED_HOSTS', CONFIG.get('ALLOWED_HOSTS')),
    default=['127.0.0.1', 'localhost'],
)


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_ckeditor_5',
    'adminsortable2',
    'sitecontent',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'sitecontent.middleware.SitePasswordMiddleware',
]

ROOT_URLCONF = 'weddingsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'sitecontent.context_processors.site_content',
            ],
        },
    },
]

WSGI_APPLICATION = 'weddingsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Jazzmin (Admin-Theme)
# https://django-jazzmin.readthedocs.io/

JAZZMIN_SETTINGS = {
    'site_title': 'V & M Hochzeit',
    'site_header': 'V & M Hochzeit',
    'site_brand': 'V & M Hochzeit',
    'welcome_sign': 'Willkommen im Verwaltungsbereich eurer Hochzeitswebsite',
    'copyright': 'V & M',
    'show_sidebar': True,
    'navigation_expanded': True,
    'language_chooser': False,
    'custom_css': 'css/admin_overrides.css',
    'icons': {
        'auth.user': 'fas fa-user',
        'auth.Group': 'fas fa-users',
        'sitecontent.textblock': 'fas fa-align-left',
        'sitecontent.siteimage': 'fas fa-image',
        'sitecontent.giftssection': 'fas fa-gift',
        'sitecontent.locationcard': 'fas fa-map-marker-alt',
        'sitecontent.timelinestep': 'fas fa-clock',
        'sitecontent.travelinfocard': 'fas fa-plane',
        'sitecontent.hotelrecommendation': 'fas fa-hotel',
        'sitecontent.faqitem': 'fas fa-question-circle',
        'sitecontent.storyitem': 'fas fa-heart',
        'sitecontent.contactperson': 'fas fa-address-book',
        'sitecontent.rsvpsubmission': 'fas fa-envelope-open-text',
    },
    'default_icon_parents': 'fas fa-chevron-circle-right',
    'default_icon_children': 'fas fa-circle',
}

JAZZMIN_UI_TWEAKS = {
    'theme': 'flatly',
}


# django-ckeditor-5 (WYSIWYG-Editor im Admin)
# https://django-ckeditor-5.readthedocs.io/

CKEDITOR_5_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['bold', 'italic', 'link', 'bulletedList', 'numberedList', '|', 'undo', 'redo'],
    },
}
